_target_: src.model.ConformerEncoderDecoder
encoder:
  _target_: src.model.ConformerEncoder
  d_in: 128
  d_hidden: 172
  kernel_size: 31
  n_layers: 16
  n_heads: 4
  dropout: 0.1
decoder:
  _target_: src.model.LSTMDecoder
  d_encoder: 172
  d_decoder: 320
  n_layers: 1
  n_tokens: 28
