defaults:
  - model: deepspeech
  - datasets: test_data_eval
  - dataloader: simple
  - transforms: only_instance
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  decoder_type: beam_search_torch
inferencer:
  device_tensors: ["spectrogram"] # which tensors should be on device (ex. GPU)
  device: cuda
  save_path: "evals"
  seed: 42
  from_pretrained: "saved/full_deepspeech_beam_search_torch_zero_to_hero_part_2_more_augs_wo_limits/model_best.pth" # path to the pretrained model
