defaults:
  - model: conformer
  - metrics: cer_wer
  - datasets: test_data_eval
  - dataloader: simple_eval
  - transforms: only_instance
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  decoder_type: argmax
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: cuda
  save_path: "evals"
  seed: 42
  from_pretrained: "saved/460h_conformer_beam_search_sft_to_360h/model_best.pth" # path to the pretrained model
