train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        p: 0.1
      - _target_: src.transforms.wav_augs.ColoredNoise
        p: 0.1
        sample_rate: 32
      - _target_: src.transforms.wav_augs.Shift
        p: 0.1
  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 80
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 40
        p: 0.1
      
  
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
